### ISSUE TITLE
支付宝点击闪退

### ISSUE THREAD

**Issue by yanpengqing** [wayu002/AlipayQRHook#14]
Process: wy.experiment.xposed, PID: 6622
    java.lang.NullPointerException: println needs a message
        at android.util.Log.println_native(Native Method)
        at android.util.Log.e(Log.java:232)
        at wy.experiment.xposed.service.CommandService$MessengerHandler.genQR(CommandService.java:88)
        at wy.experiment.xposed.service.CommandService$MessengerHandler.handleMessage(CommandService.java:64)
        at android.os.Handler.dispatchMessage(Handler.java:102)

**Comment by yanpengqing** [comment]
能不能做到一收到别人的加好友请求就自动确认添加好友。
