### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by QixianWu** [wayu002/AlipayQRHook#3]
作者有闪退的问题吗 同样微信版本也会闪退

**Comment by wayu002** [comment]
麻烦提供一下详细信息吧：
手机型号：
微信版本：
支付宝版本：
崩溃信息：
等等

**Comment by QixianWu** [comment]
MX4 4.4.2 
微信版本 支付宝 都跟你的一样。
支付宝的话，我用的是Xposed，然后一开始支付宝检测到xposed强退支付宝，我把检测方法replace了，点击生成Toast：生成二维码失败。不知道为什么失败。
微信的话是闪退，生成二维码会闪退。
报空指针，研究了一下午也没找到那里没初始化。。。

Xposed日志：
'Meizu/meizu_mx4/mx4:4.4.2/KOT49H/m75.Flyme_OS_4.2.8.2.20150422020016:user/release-keys'
Loading modules from /data/app/wy.experiment.xposed-1.apk
  Loading class wy.experiment.xposed.MainIntercept
MainIntercept====> package: com.eg.android.AlipayGphone, process: com.eg.android.AlipayGphone:push
MainIntercept====> package: com.eg.android.AlipayGphone, process: com.eg.android.AlipayGphone:tools
MainIntercept====> package: com.tencent.mm, process: com.tencent.mm:exdevice
MainIntercept====> package: com.tencent.mm, process: com.tencent.mm:push
MainIntercept====> WeChatCracker true 
MainIntercept====> package: com.tencent.mm, process: com.tencent.mm
java.lang.NullPointerException
	at wy.experiment.xposed.util.QRTool.sendQRComplete(QRTool.java:90)
	at wy.experiment.xposed.wechat.WeChatCracker.qrCodeGenerated(WeChatCracker.java:89)
	at wy.experiment.xposed.wechat.WeChatQR.notifyQRFailed(WeChatQR.java:125)
	at wy.experiment.xposed.wechat.WeChatQR.handleLoadPackage(WeChatQR.java:85)
	at wy.experiment.xposed.wechat.WeChatCracker$1.afterHookedMethod(WeChatCracker.java:104)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Native Method)
	at android.app.Application.attach(Application.java:181)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
	at android.app.Instrumentation.newApplication(Instrumentation.java:993)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4547)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5332)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by QixianWu** [comment]
> 麻烦提供一下详细信息吧：
> 手机型号：
> 微信版本：
> 支付宝版本：
> 崩溃信息：
> 等等

MX4 4.4.2 
微信版本 支付宝 都跟你的一样。
支付宝的话，我用的是Xposed，然后一开始支付宝检测到xposed强退支付宝，我把检测方法replace了，点击生成Toast：生成二维码失败。不知道为什么失败。
微信的话是闪退，生成二维码会闪退。
报空指针，研究了一下午也没找到那里没初始化。。。

Xposed日志：
'Meizu/meizu_mx4/mx4:4.4.2/KOT49H/m75.Flyme_OS_4.2.8.2.20150422020016:user/release-keys'
Loading modules from /data/app/wy.experiment.xposed-1.apk
  Loading class wy.experiment.xposed.MainIntercept
MainIntercept====> package: com.eg.android.AlipayGphone, process: com.eg.android.AlipayGphone:push
MainIntercept====> package: com.eg.android.AlipayGphone, process: com.eg.android.AlipayGphone:tools
MainIntercept====> package: com.tencent.mm, process: com.tencent.mm:exdevice
MainIntercept====> package: com.tencent.mm, process: com.tencent.mm:push
MainIntercept====> WeChatCracker true 
MainIntercept====> package: com.tencent.mm, process: com.tencent.mm
java.lang.NullPointerException
	at wy.experiment.xposed.util.QRTool.sendQRComplete(QRTool.java:90)
	at wy.experiment.xposed.wechat.WeChatCracker.qrCodeGenerated(WeChatCracker.java:89)
	at wy.experiment.xposed.wechat.WeChatQR.notifyQRFailed(WeChatQR.java:125)
	at wy.experiment.xposed.wechat.WeChatQR.handleLoadPackage(WeChatQR.java:85)
	at wy.experiment.xposed.wechat.WeChatCracker$1.afterHookedMethod(WeChatCracker.java:104)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Native Method)
	at android.app.Application.attach(Application.java:181)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
	at android.app.Instrumentation.newApplication(Instrumentation.java:993)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4547)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5332)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by wayu002** [comment]
微信是6.6.7吗，我感觉好像是hook方法的时候crash的，支付宝目前每天最多生成20次就不行了，魅族的手机还真没有，等我找到机器测试一下

**Comment by QixianWu** [comment]
> 微信是6.6.7吗，我感觉好像是hook方法的时候crash的，支付宝目前每天最多生成20次就不行了，魅族的手机还真没有，等我找到机器测试一下

微信版本是6.6.7。支付宝没成功过，应该不是次数限制的问题。

**Comment by QixianWu** [comment]
> 微信是6.6.7吗，我感觉好像是hook方法的时候crash的，支付宝目前每天最多生成20次就不行了，魅族的手机还真没有，等我找到机器测试一下

对QRTool.sendQRComplete的service判空后，xposed没报错误了，插件也不闪退了，但是和支付宝一样生成二维码失败。

**Comment by wayu002** [comment]
在WeChatQR.java->handleLoadPackage->afterHookedMethod中加日志，看一下在哪crash退出的

**Comment by yeminghua** [comment]
> > 微信是6.6.7吗，我感觉好像是hook方法的时候crash的，支付宝目前每天最多生成20次就不行了，魅族的手机还真没有，等我找到机器测试一下
> 
> 对QRTool.sendQRComplete的service判空后，xposed没报错误了，插件也不闪退了，但是和支付宝一样生成二维码失败。

解决了没有啊，华为的也闪退，微信自己就闪退

**Comment by QixianWu** [comment]
> > > 微信是6.6.7吗，我感觉好像是hook方法的时候crash的，支付宝目前每天最多生成20次就不行了，魅族的手机还真没有，等我找到机器测试一下
> > 
> > 
> > 对QRTool.sendQRComplete的service判空后，xposed没报错误了，插件也不闪退了，但是和支付宝一样生成二维码失败。
> 
> 解决了没有啊，华为的也闪退，微信自己就闪退

微信方面解决了，能生成二维码，版本6.6.7。
之前我是在android 4.4.2上操作了，现在更换了android 6.0，目测是xposed对5.0以下不兼容。
闪退你看一下日志报什么错误。

**Comment by yeminghua** [comment]
> > > 对QRTool.sendQRComplete的service判空后，xposed没报错误了，插件也不闪退了，但是和支付宝一样生成二维码失败。
> > 
> > 
> > 解决了没有啊，华为的也闪退，微信自己就闪退
> 
> 微信方面解决了，能生成二维码，版本6.6.7。
> 之前我是在android 4.4.2上操作了，现在更换了android 6.0，目测是xposed对5.0以下不兼容。
> 闪退你看一下日志报

微信自己本身闪退你是怎么解决的呢

**Comment by QixianWu** [comment]
对QRTool.sendQRComplete判空
if (service != null){
                service.send(msg);
            }
印象中是这样

**Comment by QixianWu** [comment]
> > > > 对QRTool.sendQRComplete的service判空后，xposed没报错误了，插件也不闪退了，但是和支付宝一样生成二维码失败。
> > > 
> > > 
> > > 解决了没有啊，华为的也闪退，微信自己就闪退
> > 
> > 
> > 微信方面解决了，能生成二维码，版本6.6.7。
> > 之前我是在android 4.4.2上操作了，现在更换了android 6.0，目测是xposed对5.0以下不兼容。
> > 闪退你看一下日志报
> 
> 微信自己本身闪退你是怎么解决的呢

对QRTool.sendQRComplete判空
if (service != null){
service.send(msg);
}
印象中是这样

**Comment by yeminghua** [comment]
> > > > > 对QRTool.sendQRComplete的service判空后，xposed没报错误了，插件也不闪退了，但是和支付宝一样生成二维码失败。
> > > > 
> > > > 
> > > > 解决了没有啊，华为的也闪退，微信自己就闪退
> > > 
> > > 
> > > 微信方面解决了，能生成二维码，版本6.6.7。
> > > 之前我是在android 4.4.2上操作了，现在更换了android 6.0，目测是xposed对5.0以下不兼容。
> > > 闪退你看一下日志报
> > 
> > 
> > 微信自己本身闪退你是怎么解决的呢
> 
> 对QRTool.sendQRComplete判空
> if (service != null){
> service.send(msg);
> }
> 方便加个QQ么，像你咨询几个问题2523357239，谢谢
