### ISSUE TITLE
异常：OperationType must be set

### ISSUE THREAD

**Issue by loren325** [wayu002/AlipayQRHook#7]
java.lang.IllegalStateException: OperationType must be set.
2018-12-12 16:30:43.908 4989-5071/? W/System.err:     at com.alipay.mobile.common.rpc.util.RpcInvokerUtil.getOperationTypeValue(RpcInvokerUtil.java:100014)
2018-12-12 16:30:43.908 4989-5071/? W/System.err:     at com.alipay.mobile.common.rpc.RpcInvoker.invoke(RpcInvoker.java:100084)
2018-12-12 16:30:43.908 4989-5071/? W/System.err:     at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:100011)
2018-12-12 16:30:43.908 4989-5071/? W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:913)
2018-12-12 16:30:43.908 4989-5071/? W/System.err:     at $Proxy55.toString(Unknown Source)

**Comment by lly835** [comment]
我也遇到这个问题了
